### ISSUE TITLE
Make a link to MANUAL.md

### ISSUE THREAD

**Issue by tseemann** [DerrickWood/kraken2#1]
Can you direct link to the markdown manual in docs/ so we can read it on github?

**Comment by DerrickWood** [comment]
You can presently just view the markdown manual to read it on github: https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown

Eventually, I plan to actually get a website together for Kraken 2 and will link directly to the HTML version there. The github markdown display doesn't completely play nice with some of the things I've done in the manual, and so I've a preference for encouraging people to view the HTML rather than github's markdown version.

**Comment by tseemann** [comment]
I still don't understand why you wouldn't just make a link to it from README.md if you want people to use it anyway?    We currently have to click around? Or am I missing something?

**Comment by DerrickWood** [comment]
I don't actually want people to use the MANUAL.markdown file (although I can't really stop them). I would prefer they review the MANUAL.html - which has the table of contents and interprets my LaTeX-y stuff properly - but I don't have it set up on an external site just yet. I should have that up over the weekend at the latest, and will update the README.md to point people to that site then.
