### ISSUE TITLE
Unable to download the taxonomy data

### ISSUE THREAD

**Issue by swamyrakesh** [DerrickWood/kraken2#107]
While I was trying to download the taxonomy file, I have been getting the rsync error. 

**kraken2-build --download-taxonomy --db KRKBD2**
Downloading nucleotide est accession to taxon map...rsync: failed to connect to ftp.ncbi.nlm.nih.gov (130.14.250.12): Operation timed out (60)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

Kraken version 2.0.7-beta
Copyright 2013-2018, Derrick Wood (dwood@cs.jhu.edu)

**Comment by Yiheng323** [comment]
I think most likely it is going to be fixed soon but there was an answer in one of the issues of kraken1 here [https://github.com/DerrickWood/kraken/issues/55](url). Because NCBI recently updated location for all their taxonomy files so they need some time to fix the code accordingly. You can manually download the taxonomy files as referring to the issue above, and also need to download the dump files (NCBI changed location a few hours ago!):

cd $$DBNAME/taxonomy
wget [https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/new_taxdump/new_taxdump.tar.gz](url)
wget [https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_gb.accession2taxid.gz](url)
wget [https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_wgs.accession2taxid.gz](url)
touch accmap.dlflag # I am not sure if it is necessary but I think --clean will do the work if it is not.

Then the --download-library and --build flag worked for me when I download fungi database for a test.
Cheers

**Comment by jenniferlu717** [comment]
@Yiheng323 is correct in all of the above. 

However I believe the issue is actually an rsync issue.

@swamyrakesh try rerunning the code with the `--use-ftp` flag?

`kraken2-build --download-taxonomy --db KRKBD2 --use-ftp`
