### ISSUE TITLE
Silva, RDP and Greengenes

### ISSUE THREAD

**Issue by davidbio** [DerrickWood/kraken2#108]
Hi,

I am trying to evaluate the special databases: RDP, GreenGenes and Silva.
Kraken version 2.0.8-beta

For testing, I am using the simulated amplicon data "50000 reads LC, MC, HC 200 V3 with errors" from "Assessment of Common and Emerging Bioinformatics Pipelines for Targeted Metagenomics" [https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0169563](url)

First of all, I get pretty decent results with Kraken1 and Kraken2 and their corresponding standard databases at the family and genus levels:

Tool | Rank | Complexity | Precision | Sensitivity | F1-Measure
-|-|-|-|-|-
Kraken1 STD | family | MC | 0.9914227112 | 0.9650506191 | 0.9780589251
Kraken1 STD | genus | MC | 0.9819969035 | 0.550969697 | 0.7058869204
Kraken1 STD | family | HC | 0.9774786548 | 0.9165134992 | 0.9460148823
Kraken1 STD | genus | HC | 0.9612145005 | 0.7986539772 | 0.8724263131
Kraken1 STD | family | LC | 0.9750237049 | 0.9263733339 | 0.9500761195
Kraken1 STD | genus | LC | 0.9479994519 | 0.5708097851 | 0.712567912
Kraken2 STD | family | MC | 0.9795131555 | 0.9747556172 | 0.9771285954
Kraken2 STD | genus | MC | 0.9316588174 | 0.3656302625 | 0.5251607575
Kraken2 STD | family | HC  | 0.9446378002 | 0.9211408335 | 0.9327413605
Kraken2 STD | genus | HC | 0.9007564885 | 0.806424216 | 0.8509841321
Kraken2 STD | family | LC | 0.9542797406 | 0.9346386109 | 0.9443570607
Kraken2 STD | genus | LC | 0.8921882909 | 0.5648969127 | 0.6917844061

With Silva, RDP and GreenGenes, however, I get very poor classification results:
- Nearly no correct classifications (up to 50 maybe).
- More than half of the dataset is classified incorrectly (many bacteria are classified as eukaryotes).
- The rest can not be classified.

The scores I obtain with the standard database (see table above) make sense, which makes me believe that I am missing something when creating the "special" databases or when performing the search on the amplicon data. I use the standard commands indicated in the manual. Does anyone have experience with this?

Any help/comment is appreciated!

Best,
David

**Comment by jenniferlu717** [comment]
Generally, note that the 16S Silva, RDP, and Greengenes databases are NOT curated by us. We only provide support to classify reads against these databases using Kraken. Their sequences and taxonomies are independently curated/formulated and all three are different in many ways from one another AND drastically different from NCBI Refseq/Genbank.
 
1. Eukaryotes are not in the 16S databases, so I'm not sure what you mean by that. If you are trying to add the 16S databases to the eukaryotic refseq database, you will have a problem because the taxonomies are drastically different. 
2. I have found that the 16S databases do NOT all contain a comprehensive/consistent selection of the bacterial genomes. Some genomes may be missing and some even have different naming schemes entirely. I personally prefer NCBI's refseq (which is what the Kraken1/Kraken2 standard databases use). 

The issue isn't with the Kraken2 building of the databases but it seems to be an issue with the 16S databases themselves. I checked the files downloaded directly from the 16S databases and those even have these naming/taxonomy issues.
