### ISSUE TITLE
16S SILVA database now free of licencing restrictions

### ISSUE THREAD

**Issue by dswan** [DerrickWood/kraken2#11]
I noticed on the website for Kraken2 under 'specialist databases':

"Note that these databases may have licensing restrictions regarding their data, and it is your responsibility to ensure you are in compliance with those restrictions; please visit the databases' websites for further details."

This was presumably a reference to the dual-licencing of SILVA, which was not previously available without licences for commercial use. This restriction is now gone, it is part of [ELIXIR and a 'Core Data Resource'](https://www.elixir-europe.org/news/brenda-and-silva-elixir-core-data)

**Comment by DerrickWood** [comment]
That page (and SILVA's website) indicates that the commercial restriction will be lifted as of the next DB release, scheduled for later this year. So that's not _quite_ true as of yet.

I actually don't remember if it was just SILVA's licensing that prompted me to add that notice, though. In any event, it's probably worth leaving in the docs just to ensure people check out the websites for the stuff they're downloading.
