### ISSUE TITLE
seqid2taxid.map file

### ISSUE THREAD

**Issue by sxh1136** [DerrickWood/kraken2#129]
Hi developers,

I'm am trying to run Bracken using a custom Kraken2 database. I downloaded this database and it only includes the hash.k2d, opts.k2d and the taxo.k2d files. I have since downloaded the ncbi taxonomy and the original fna sequence files. When I try to run bracken-build it stops part way due to a seqid2taxid.map not existing. Is there a way for me to quickly obtain this file without building the database from scratch?

Thank you in advance

**Comment by jenniferlu717** [comment]
The seqid2taxid map file is generated in the first step of building so if you build with just the fna files and the taxonomy in a separate folder and cancel the kraken2-build right after the seqid2taxid is generated, you will have the necessary file.

**Comment by sxh1136** [comment]
Thank you for your help. 

When I try to build the db I get this:

`No preliminary seqid/taxid mapping files found`

I assume this is because I just downloaded the fna files but didn't add to library? How can i add them to the library since the manual says that it only accepts fasta files?

**Comment by jenniferlu717** [comment]
.fna files sre fasta files. Simply add to library using kraken2-build --add-to-library (use the loop example in the manual) and build after

**Comment by dmsalsgh97** [comment]
Hi, I think I'm on the exactly same issue. I downloaded kraken2-microbial-fatfree pre-built kraken db from Loman lab. (It only contains 3 k2d files, there is no seqid2taxid file).
Next, to generate bracken k-mer distribute file, I need seqid2taxid.map files for the kraken2-microbial-fatfree database...
But, I don't have .fna files for the kraken2-microbial-fatfree database because I didn't build the db myself.  
In this case, how can I generate the right seqid2taxid.map files or get it? 
Or the only way is to generate microbiome kraken db on my self? 

Thank you for your advice :)
