### ISSUE TITLE
What is "x" replacing the genome sequence

### ISSUE THREAD

**Issue by mu-bio** [DerrickWood/kraken2#151]
I'm using the standard Kraken 2 database.
What is meant by "x" character replacing the eukaryotic genome sequence in library.fna?
What is different from N?

**Comment by jenniferlu717** [comment]
Based on prior requests, we use x to replace low-complexity sequences rather than N. 

In previous versions of kraken, we used N, but that adds a bit of confusion as some sequences have Ns in them and we wanted to distinguish between the masked areas in the original sequence and the low-complexity sequences that we mask.

If you do not want low-complexity sequences to be removed, simply add the --no-masking option when downloading a library.
