### ISSUE TITLE
Question: does Kraken2 SILVA database contain 18S?

### ISSUE THREAD

**Issue by l-yampolsky** [DerrickWood/kraken2#182]
If I understand SILVA data correctly, NR99 contains both prokaryotic 16S and eukaryotic 18S sequences. There are some indications in the manual that Kraken 2 database silva, does too, for example it is described as "using the Small subunit NR99 sequence set" (as opposed to more specific description as "16S" for the other 2 16S databases. 
Just want to clarify - thanks!

**Comment by jenniferlu717** [comment]
No, it does not, but you could try and build the SILVA 18S if you get the same filetypes that we use for the 16S SILVA build.

**Comment by SumTot** [comment]
Hello, I know this issue is already closed...but I wonder if you know of someone that has got the necessary filetypes for SILVA 18S.
I would like to include them in my analysis with Kraken2.
If you don't know of anyone, could you explain to me the way to do it? I am pretty new downloading databases...
Thanks a lot!

**Comment by timregan** [comment]
Would you mind elaborating on this please? I am also interested in using Kraken2 for 18S sequences. Are these not available from SILVA?
