### ISSUE TITLE
Is it normal for the progress of database building?

### ISSUE THREAD

**Issue by Lily-WL** [DerrickWood/kraken2#23]
Dear developer,
The building progress stop in the step " Step 1/2: Performing rsync file transfer of requested files" for more than 24 hours. Is it normal? The command is as follows:

`./kraken2-build --standard --threads 40 --db /opt/kraken2/database`

> --2018-07-08 15:35:38--  ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/nucl_est.accession2taxid.gz
>            => “nucl_est.accession2taxid.gz”
> ........................................
> (The output is omitted)
> 2018-07-08 17:59:27 (0.00 B/s) - “taxdump.tar.gz” 已保存 [43921242]
> 
> Downloaded taxonomy tree data
> Uncompressing taxonomy data... done.
> Untarring taxonomy tree data... done.
> Step 1/2: Performing rsync file transfer of requested files
> Rsync file transfer complete.
> Step 2/2: Assigning taxonomic IDs to sequences
> Processed 272 projects (408 sequences, 687.34 Mbp)... done.
> All files processed, cleaning up extra sequence files... done, library complete.
> Masking low-complexity regions of downloaded library...done.
> Step 1/2: Performing rsync file transfer of requested files

**Comment by DerrickWood** [comment]
24 hours is indeed a bit much for that download, but it's likely due to network issues that I probably can't do much about. For reference, the first "rsync file transfer" shown in the output above is the archaeal download, which takes about 35 seconds to download and process from my laptop. The bacterial download (the next one that your output stops at) is a good deal longer, and took me just under an hour a few minutes ago.

**Comment by Lily-WL** [comment]
Thank you very much for your reply. I tried to install "rsync" through yum and the progress can continue well now.

**Comment by Lily-WL** [comment]
Thank you for your reply. And I tried to install "rsync". Seems it works a bit and the database building finished.
