### ISSUE TITLE
Standard kraken database

### ISSUE THREAD

**Issue by MjelleLab** [DerrickWood/kraken2#239]
Hi,
Where can I find the standard kraken database as a fasta file, including a taxonomy file. I would like to use it as input in the Qiime2 pipeline for comparison. 
Best,

**Comment by jenniferlu717** [comment]
The standard kraken database can be downloaded/built using 
`kraken2-build --download-taxonomy --db .`
`kraken2-build --standard --db .`
but we do not provide the complete database for download due to the size. We (JHU Genomics group) only provide the minikraken database currently

However, the loman lab does provide the standard database as maxikraken here:   https://lomanlab.github.io/mockcommunity/mc_databases.html but this only has the already built database, not the sequence files or the taxonomy folder.
