### ISSUE TITLE
Kraken2 Report File- fragments assigned directly to this taxon

### ISSUE THREAD

**Issue by SumTot** [DerrickWood/kraken2#242]
Hello!
If the report file is like that:
_1.Percentage of fragments covered by the clade rooted at this taxon
2. Number of fragments covered by the clade rooted at this taxon
3. Number of fragments assigned directly to this taxon
4. A rank code, indicating (U)nclassified, (R)oot, (D)omain, (K)ingdom,
   (P)hylum, (C)lass, (O)rder, (F)amily, (G)enus, or (S)pecies.
   Taxa that are not at any of these 10 ranks have a rank code that is
   formed by using the rank code of the closest ancestor rank with
   a number indicating the distance from that rank.  E.g., "G2" is a
   rank code indicating a taxon is between genus and species and the
   grandparent taxon is at the genus rank.
5. NCBI taxonomic ID number
6. Indented scientific name_

Opening my report file I have found some taxa that are **0** in the number of fragments assigned directly to a taxon (point 3). However they contain a number of fragments covered by the clade (point 2).

How can it be possible?
Thanks!

**Comment by jenniferlu717** [comment]
This happens when sequences are more specifically classified.
For example, if you have 100 reads, where Kraken2 assigned 50 to Bacillus anthracis and 50 to Bacillus cereus, then your report will read (columns 2,3,4,6):

100 0 G Bacillus
50 50 S Bacillus anthracis
50 50 S Bacillus cereus  

However, if there are 100 reads and 10 are identical to both B. anthracis and B. cereus, then Kraken will assign them directly to Bacillus and the report will read:
100 10 G Bacillus
45 45 S Bacillus anthracis
45 45 S Bacillus cereus

**Comment by SumTot** [comment]
Thanks! It´s very clear now :)
