### ISSUE TITLE
Unable to download the env_nt library

### ISSUE THREAD

**Issue by glajoie1** [DerrickWood/kraken2#261]
The env_nt library is specified as a custom database on the kraken2 manual, but I'm unable to download it.

I'm using the Kraken version 2.0.9-beta.

Command:
kraken2-build --download-library env_nt --db envntdb --use-ftp --threads 8
Error message:
Unknown library type "env_nt"

When adding the option directly into the kraken2-build script, produces error "Unsupported library. Valid options are: archaea bacteria viral fungi plant protozoa human plasmid nr nt UniVec UniVec_Core"

Thanks for your help.

**Comment by DerrickWood** [comment]
In March 2020 (or slightly earlier), NCBI stopped putting env_nt and env_nr data in the ftp://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/ directory (where we get the data for our larger genomic libraries). Because of that, we removed Kraken support for the download of those two libraries in v2.0.9. The wiki and 2.0.9 manual have been updated, but it looks like the Kraken 2 website was still using the 2.0.8 manual which had outdated information. Sorry about that confusion - we've updated the website's manual link to point to our wiki.
