### ISSUE TITLE
kraken2 paired files error

### ISSUE THREAD

**Issue by bioinfo17** [DerrickWood/kraken2#296]
Hi,

I'm using kraken2 (Kraken version 2.0.9-beta) under conda environment. When I run:

 kraken2 --db ../minikraken_8GB_20200312 --threads 32 --output P2.kraken2 --report-zero-counts P2.report --gzip-compressed --paired FCH5NCCDSXY_L3_WHRDBACtdaRBAAAB-92_1.fq.gz FCH5NCCDSXY_L3_WHRDBACtdaRBAAAB-92_2.fq.gz

I get the following error:

kraken2: --paired requires positive and even number filenames

I have changed the order of the parameters but I keep getting the same error.

Please advise.

**Comment by jenniferlu717** [comment]
You are missing the --report parameter. --report-zero-counts and --report should be used together. --report is the name of the report, --report-zero-counts just tells the script to include 0 counts.

**Comment by JCSzamosi** [comment]
Is it the case that if you use the `--paired` flag, you will get the error message `kraken2: --paired requires positive and even number filenames` no matter what the actual problem with your call to kraken is?

I'm getting the same error despite giving two filenames. Using v2.1.3, my command is:

```
kraken2 classify --db data/krakenDBs/built_nt/ \
     --threads 5 \
     --output tst.out \
     --report tst_report.txt \
     --use-names \
     --paired \
     results/06_trimmed/pepper/RS-4_10pc_trimmed_R1.fastq \
     results/06_trimmed/pepper/RS-4_10pc_trimmed_R2.fastq
```

Can you help me identify what the problem is?
