### ISSUE TITLE
'Online' classifivation with kraken 2

### ISSUE THREAD

**Issue by Midnighter** [DerrickWood/kraken2#305]
Hi,

I'm trying to classify a large number of samples using a pipeline and in the kraken step it takes almost as much time to load the database into memory as it does to classify all the reads. The situation can be slightly improved by putting the database on an SSD.

This made me think, though, if it is somehow possible to maintain the database in memory or have kraken run in a more 'server' like fashion where I would send sequences to a running process and retrieve output. Do you know of any possibilities or is anything like this planned?

**Comment by zmunro** [comment]
The best way to do this I have found is to create a ram backed disk and copy the database there. Here is a link to a page describing how to do this: [https://www.jamescoyle.net/how-to/943-create-a-ram-disk-in-linux](https://www.jamescoyle.net/how-to/943-create-a-ram-disk-in-linux)

When your "server" starts up, you copy the database into the directory you mounted the ramdisk to (since that directory is erased whenever the machine restarts), and then point kraken there. Zero load time :+1:

**Comment by Midnighter** [comment]
Awesome, thank you very much :pray:
