### ISSUE TITLE
relative abundance

### ISSUE THREAD

**Issue by superhu0** [DerrickWood/kraken2#32]
Hi 
I wonder how to calculate the relative abundance with the report-mpa-style table to compare different samples.
any idea?
hu 
thanks

**Comment by tseemann** [comment]
I was under the impression that Kraken was *not* suitable for abundance estimation?

https://genomebiology.biomedcentral.com/articles/10.1186/gb-2014-15-3-r46

**Comment by DerrickWood** [comment]
Kraken is solving a problem not directly related to the abundance estimation problem, that is, we are trying to label as much of the sequence data as we have evidence for. As we discussed in the paper, some programs solve abundance estimation directly while labelling only a small subset of reads. This is possible in part due to the use of marker genes, and often requires a somewhat curated database of those genes. Kraken allows labelling of each read, and because we also allow custom databases, along with labels that aren't at the leaves of the taxonomic tree, it's not trivial to make a robust solution to allow abundance estimation with Kraken.

That said, I've not explored the problem deeply, and someone (perhaps @jenniferlu717) may have insight I don't here. Bracken's functionality may get you most of the way to a relative abundance, although I suspect a normalization must also be done to account for differences in genome lengths.

**Comment by jenniferlu717** [comment]
Bracken was written to allow for approximate relative abundance with Kraken, using their Kraken report output (not the mpa report). You can find more information and links to the paper/code here: https://ccb.jhu.edu/software/bracken/.

That being said, it is approximate and will give you approximate reads at a chosen taxonomic level. The reads are not normalized by genome length.

**Comment by FCMicrobes** [comment]
I think that will be very great to add genome length normalisation because a lot of people are using kraken/bracken to estimate taxonomic composition of meta-genome dataset. Another big improve will be to add the breath of coverage information, that could help to filter out false positive detection.
Will it be easy to implement? What do you think?

**Comment by jenniferlu717** [comment]
Breadth of coverage would not be as simple. Genome length may be. I'm working on other improvements to the speed of the building process for Bracken first however.

**Comment by zburcham** [comment]
Hi @jenniferlu717 , has there been any updates the relative abundance estimations for Braken? Namely, normalization and/or being able to use the mpa-style output?

**Comment by jenniferlu717** [comment]
I've not decided to include normalization, namely for the fact that its highly dependent on genomes within a species being similar in genome length (for species where genome lengths vary significantly, it wouldn't make much sense to normalize).

mpa-style output is something that could be possible, but is not currently being worked on, but for these sorts of requests, make an issue on the Bracken github and I might be able to get around to it soon.
