### ISSUE TITLE
kraken2-build standard exits without building

### ISSUE THREAD

**Issue by eyashiro** [DerrickWood/kraken2#345]
Hello,

(kraken v2.1.0)
I am trying to build a database using the standard option, but the workflow never finishes.
I noticed that the workflow starts at the "Downloading taxonomy tree data..." step, and skips the download of the accession2taxid files. After that it aborts the build step stating that the accession2taxid files were not found.

I noticed also that the option "--skip-maps" is set to True in the standard_installation.sh line 29. If I understood correctly, that would automatically make the download_taxonomy.sh skip the download for accession2taxid files.

Is the kraken2-build standard workflow supposed to work like it did in my case?

Below I copy-paste the command and output.

Thank you for your help in getting the database set up.

Kind regards, Erika

$ kraken2-build --standard --threads 10 --db /home/admin/ey/Software/kraken2/kraken2_db_2020-10-21
Downloading taxonomy tree data... done.
Untarring taxonomy tree data... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 392 projects (606 sequences, 1.02 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 21974 projects (48486 sequences, 89.57 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 10388 projects (13011 sequences, 387.10 Mbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Masking low-complexity regions of downloaded library... done.
Downloading plasmid files from FTP... done.
Masking low-complexity regions of downloaded library... done.
mv: replace 'assembly_summary.txt', overriding mode 0444 (r--r--r--)? y
Step 1/2: Performing rsync file transfer of requested files
Rsync file transfer complete.
Step 2/2: Assigning taxonomic IDs to sequences
Processed 1 project (639 sequences, 3.27 Gbp)... done.
All files processed, cleaning up extra sequence files... done, library complete.
Downloading UniVec_Core data from server... done.
Adding taxonomy ID of 28384 to all sequences... done.
Masking low-complexity regions of downloaded library... done.
Creating sequence ID to taxonomy ID map (step 1)...
Accession to taxid map files are required to build this DB.
Run 'kraken2-build --db /home/admin/ey/Software/kraken2/kraken2_db_2020-10-21 --download-taxonomy' again?
$

**Comment by DerrickWood** [comment]
Hi Erika,

In the standard database build, the taxid assignment comes from the `assembly_summary.txt` files, rather than needing separate accession to taxid mappings. Thus, we skip the downloading of those maps for the standard build, given that they are several GB in size. In your case, the build appears to think one or more sequences still require these mapping files (i.e., some sequences somehow lacked the needed taxid assigments in the `assembly_summary.txt` file). Such files should be listed in the `$DBNAME/accmap_file.tmp` file - the fact that this file was generated with nonzero content is what triggered the "Accession to taxid map files are required to build this DB." statement.

In your example, `$DBNAME` would be `/home/admin/ey/Software/kraken2/kraken2_db_2020-10-21`; could you share the output of the command `head /home/admin/ey/Software/kraken2/kraken2_db_2020-10-21/accmap_file.tmp`? That could help us figure out what might have gone wrong here. Additionally, I notice your output has a `mv: replace 'assembly_summary.txt', overriding mode 0444 (r--r--r--)? y` line around the point of the plasmid library download, which might indicate that there was already an existing attempt to download plasmid data. You may also want to try running your command with a brand new database name to see if a clean DB directory might fix the problem, which could be due to a mismatch between the `assembly_summary.txt` file used to generate the initial set of files to process and the final set being used in the `Creating sequence ID to taxonomy ID map` step.


Derrick

**Comment by eyashiro** [comment]
Hello Derrick,

Thank you very much for responding back to me.

I tried to rerun the kraken2-build in a fresh directory twice and I always get the same output.
Below is the output from the accmap_file.tmp:
 head accmap_file.tmp 
NC_004464.2	NC_004464
NC_004965.1	NC_004965
NC_000906.2	NC_000906
NC_002092.1	NC_002092
NC_006997.1	NC_006997
NC_002119.1	NC_002119
NC_009034.1	NC_009034
NC_005249.1	NC_005249
NC_005020.1	NC_005020
NC_002635.1	NC_002635

Also, I noticed that all of the assembly_summary.txt files in the library directories are r--r--r, and that is why, after plasmid build is done and the script moves on to human build, kraken2-build asks me whether it can move file x to assembly_summary.txt when building the human summary file. I was able to manually reproduce this r--r--r-- when I used the option to rsync rather than ftp the assembly_summary.txt file. So for some reason, kraken2-build is preferring to use rsync rather than ftp to download the assembly_summary.txt files?

Thanks again for your insights on how to get the database built.

Kind regards, Erika

**Comment by DerrickWood** [comment]
Hi Erika,

It turns out that the plasmid library is a bit different than many of the other library downloads (such as bacteria or plant) due to its organization on the NCBI FTP site. As a result, the `--skip-maps` option has to be removed from the Kraken 2 standard database build script for the foreseeable future. This may mean slightly larger downloads, but should avoid the problems you've run into. This should be fixed as of v2.1.1.


Derrick
