### ISSUE TITLE
Kraken2 taxonomy does not follow standard NCBI taxonomy format

### ISSUE THREAD

**Issue by davve2** [DerrickWood/kraken2#350]
I´m developing a program that makes use of kraken2 downstream, however I discovered that kraken2 add it´s own names.dmp and nodes.dmp format by adding a column with a dash "-" into the files. This causes problems when using softwares written to use standard NCBI format.  Related issues #329 and #349

Is there any specific reason why the dash is added?

**Comment by DerrickWood** [comment]
It sounds like you're referring to the *.dmp files created by Kraken 2 as part of the process of creating 16S databases. These files are only created to facilitate Kraken 2's building of its internal taxonomy (stored in the non-text file taxo.k2d). We use dashes because Kraken doesn't need the fields marked with a dash (but does need to put fields in their proper positions). These *.dmp files are for Kraken's use only, and we're not planning changes to make them follow NCBI formatting.
