### ISSUE TITLE
Limit kraken search to only specific taxon(s) in the database

### ISSUE THREAD

**Issue by kilojarek** [DerrickWood/kraken2#360]
Hi,

we are using kraken in a different way than is described on the tin :-) We have a list of reads I want to match agains a custom database made of rodent whole-genome sequences. The goal is to find a match in **each** of the genomes in the database for each read from my query. In this case I am treating it more like a BLAST search.

But kraken, as far as I can tell, only produces a single taxid for each read (plus a parent taxon for the best match). Can I force it to find matches in each of the taxons in my database? Or at least can we specify a taxon id, present in my database, against which kraken should attempt to find a match? Importantly, we don't know beforehand whether there _is_ a match in any of my genomes to any of my loci.

If not, the alternative we are thinking of is to prepare many single-genome kraken databases and run our search against each. This is computationally expensive but still should be way quicker than building a BLAST database and running our reads against it (we have tens of thousands of reads to match).

**Comment by mihkelvaher** [comment]
Not a kraken dev, just here to comment.
Single-genome kraken databases probably won't work because all of the k-mers would remain on the species level since there aren't any other genomes to have common k-mers with that would be moved towards the root.

I didn't quite understand what the output should look like but it seems such a custom approach would be better done by comparing k-mers lists of different genomes to a k-mer list of reads and counting common k-mers between the lists.

**Comment by kilojarek** [comment]
Thank you. Good point, although in our case we'd use singe-genome kraken database for a check whether there is a match or not - we are OK with all the matches being the same species.
We have discussed this a bit more and we are pretty sure we cannot do what we want with kraken and need to go for BLAST. Thanks again!
