### ISSUE TITLE
Pre-build databases correct?

### ISSUE THREAD

**Issue by Sofie8** [DerrickWood/kraken2#388]
Hi,

Is it possible that I don't see any fungi reads in the pre-build database named 'Standard plus protozoa, fungi & plant', [94.3 Gb index size](https://genome-idx.s3.amazonaws.com/kraken/pluspfp_20201202/inspect.txt). I also question if the protozoa are there. Can you have a look please?
I am now downloading the separate databases, prior to build.  But should I merge them before running kraken2-build build?

kraken2-build --download-library bacteria --db bacteriadb --threads 36
kraken2-build --download-library archaea --db archaeadb --threads 36
kraken2-build --download-library fungi --db fungidb --threads 36
kraken2-build --download-library protozoa --db protozoadb --threads 36
kraken2-build --download-library plant --db plantdb --threads 36
kraken2-build --download-library plasmid --db plasmiddb --threads 36
kraken2-build --download-library viral --db viraldb --threads 36
kraken2-build --download-library human --db humandb --threads 36
kraken2-build --download-library UniVec --db univecdb --threads 36

cat bacteriadb archaeadb fungidb protozoadb plantdb plasmiddb viraldb humandb univecdb > finaldb
kraken2-build --build --db finaldb --threads 36

Thanks,
Sofie

**Comment by mihkelvaher** [comment]
If you want to have all of the sequences in the same database, just download them to the same place
```
kraken2-build --download-library bacteria --db finaldb --threads 36
kraken2-build --download-library archaea --db finaldb --threads 36
kraken2-build --download-library fungi --db finaldb --threads 36
...
```

`cat bacteriadb archaeadb...` won't work because the databases (bacteriadb, archaeadb etc) are directories.

If you download them separately, then you need to build each of them separately. If you've already downloaded all of them a hacky/messy way to merge them into one of the existing dirs (for example bacteriadb) is to use
`kraken2-build --add-to-library chr1.fa --db bacteriadb`
where instead of `chr1.fa` you add the fasta files from other database library dirs (for example archaeadb//library/archaea/library.fna). And then build.
Again, this is a messy approach and it would be better to download them all into the final dir in the first place.

**Comment by jenniferlu717** [comment]
@Sofie8 I believe we noted this issue and corrected it in the recent release of the prebuilt database, but for future reference, feel free to open an issue here: https://github.com/BenLangmead/aws-indexes
