### ISSUE TITLE
Difference between unclassified and root/other sequences in fungal RNA-Seq data

### ISSUE THREAD

**Issue by ARW-UBT** [DerrickWood/kraken2#393]
Hi, 
I am classifying RNA-Seq paired end reads from a fungus using the standard db (Ben Langmead Index zone) which covers archaea, bacteria, viral, plasmid, human, UniVec_Core. 

The report indicates a considerable part of 'other sequences' (R2) within the paired end reads in addition to the 'unclassified' ones (as expected because the fungus is not oart of the standard db). 
What is the difference between 'unclassified' and 'other sequences', which are outside the 'cellular organisms'?

 42.92	6396103	6396103	U	0	unclassified
 57.08	8507152	281303	R	1	root
 42.06	6268065	0	R1	2787854	  other entries
 42.06	6268065	6268064	R2	28384	    other sequences
  0.00	1	0	R3	36549	      plasmids
  0.00	1	1	S	45419	        Plasmid pFA6
 13.03	1942627	5530	R1	131567	  cellular organisms
  7.00	1043299	0	D	2759	    Eukaryota
  7.00	1043299	0	D1	33154	      Opisthokonta

My aim is to get rid of bacterial sequences (and possibly human contamination) in order to assemble a fungal reference transcriptome from 'purified' reads. 

Related question to this: 
Does anyone have experience with the order of classification/transcriptome assembly? 
Does Kraken2 perfom better on transcriptome assemblies compared to raw fastq data (with sequence higher error rates). 
Method 1: classify fastq data by Kraken2, then assemble transcriptome by Trinity;
Method 2: assemble transcriptome from fastq by Trinity, then classify resulting transcripts (fasta) by Kraken2;

Thank you for any contribution!

**Comment by jenniferlu717** [comment]
The "other sequences" are any sequences in the UniVec_Core sequences in the database. These are sequences that are vectors/adaptors/linkers/primers that can typically contaminate any sequencing dataset. 

Unclassified reads are any reads that do not have kmers matching the database at all. 

For our lab, we typically do not assemble first before classification. We do classification first, but if there is a large fraction of unclassified reads, we will assemble. 

However, it may be that Kraken would have better accuracy in classifying an assembled genome rather than the individual reads, but it might take longer. I might suggest classifying first and then taking subsets of reads (based on their classification) for assembly. For example, taking all unclassified reads or taking all reads of a particular genome of interest and assemble from there. You'll have fewer reads to try to assemble. You can extract reads classified using KrakenTools (which we also developed): https://github.com/jenniferlu717/KrakenTools 

However, Kraken is designed such that you would not need significant overlap between reads for an organism to be identified. So I don't expect you would be able to assembly reads if the reads are scattered across a genome and non-overlapping. 

Hope that helps.

**Comment by vragh** [comment]
@ARW-UBT what did you end up doing? For transcriptome assembly (I presume you're going _de novo_) I guess it's better to classify first and _then_ assemble. This would minimize chimeric contigs, and reduce the assembly size if the data is heavily contaminated.

I also wanted to ask, what confidence threshold did you use?

**Comment by ARW-UBT** [comment]
@vragh 
Yes, the reades were first classified and then used for de novo assembly by Trinity. The kraken confidence filter was set to 0.1 
Best,

**Comment by vragh** [comment]
@ARW-UBT thanks for the prompt reply. That's great, and I'm very glad the setup worked out nicely (and it has at my end also).

**Comment by vragh** [comment]
@ARW-UBT , @jenniferlu717 ,

Just to clarify, setting the confidence value to 0.1 would be `--confidence 0.1` right? (And not `--confidence 0.9`.)

I just happened to see #167 , and I've gotten very confused since the screenshot that OP shared quotes @jenniferlu717 suggesting that one use 0.9 but then they replied to the post stating something else.

Sorry for bothering both of you with this again.

**Comment by waalkes** [comment]
Is there any way to exclude the other sequences from Kraken2 output?  So it doesn't cloud the percentages?

**Comment by vebaev** [comment]
> @vragh Yes, the reades were first classified and then used for de novo assembly by Trinity. The kraken confidence filter was set to 0.1 Best,

Hi, how you extract unclassified reads to feed to the assembler?
