### ISSUE TITLE
The Fungi database failed to install correctly.

### ISSUE THREAD

**Issue by maculatus** [DerrickWood/kraken2#398]
Hello,
I am trying to install the fungi database by itself. I started to install the taxonomy:
kraken2-build --download-taxonomy --db fungi/
and later build the library:
kraeken2-build --download-library fungi --db fungi/
However, they are only two files: library and taxonomy. They are populated with their files but the hash.k2d, opts.k2d, seqid2taxid.map and taxo.k2d were not created. Do I missing something when I build the database?

**Comment by AGalanis97** [comment]
Hi @maculatus ,

from the manual you need to follow the last step of database building:

> 3. Once your library is finalized, you need to build the database. This can be done with the command:
> 
> ` kraken2-build --build --db $DBNAME`
> 

So you need to run the command kraken2-build --build --db fungi/ . If you have threads to spare, use them to speed things up ;) Also consider evaluating the confidence threshold for your classification :)

**Comment by maculatus** [comment]
Thanks! I missed that part.
Cheers
Gustavo

**Comment by maculatus** [comment]
Thanks for your reply. I got some funny results with the standard database.
I got a lot of my sequences as H. sapiens. Many of the same contigs when I
blasted against the nt database came back as fungi. I am preparing this
database that contains Fungi to correct this. Is it a way to increase
constraints?

**Comment by AGalanis97** [comment]
You should always keep in mind that your results reflect what's in the datavase: if something doesn't exist in it, you won't see it in the results.
In general it is better to use databases that contain as many species as possible. There are many examples of this such as here: https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-6592-2
I use the nt for the analyses I am doing but it takes about 16-24 hours to build (on my system). Otherwise, if all you care about is fungi alone, you can use the fungi refseq. I am not sure if the fungal database contains the human genome but it may be worth removing human reads with bbduk to reduce potential false positives. You can also find some preindexed databases here: https://benlangmead.github.io/aws-indexes/k2

The way to increase constraints its through the confidence threshold. Increasing it will reduce the number of false positives, even at 0.05 or 0.1 the drop is very large. But you'll lose some sensitivity, not too much but it is worth keeping in mind.

**Comment by jenniferlu717** [comment]
Thank you @AGalanis97 for all of the helpful tips/answers! (Let me know if you would like to contribute to our wiki's FAQ  - email me at jennifer.lu717@gmail.com) 

@maculatus I'm going to close this issue for now but feel free to make a new issue if you have any other questions/concerns/
