### ISSUE TITLE
unexpected difference in results with two different custom kraken2 databases

### ISSUE THREAD

**Issue by SonWende** [DerrickWood/kraken2#403]
Dear Kraken2 Team,

i apologize for the long post, but i cant figure out why my two custom databases give me such different results in areas, where they should be the same. Can you maybe help me figure out what is going on? 

Here is the setup:
We have sequenced several rhizobial metagenomes with a sequencing depth of 30G. I wanted perform a comparison between the community analysis from Amplicon Sequencing with 16S and ITS and the abundance estimation with kraken/bracken. 

For that i built microbial database with kraken2-build, including the libraries bacteria, archaea, viral, fungi, protozoa and Univec_core. But the default library of fungi only included 58 refeq genomes (those tagged as either ”Complete” or “Chromosome”). Since I wanted a broader capture of the fungi, I tried out an extended microbial database. It contains the exact same libraries, except for fungi, where it includes all “representative” and “reference” genomes from refseq (this includes then 299 instead of 58 fungal Genomes)

There are a few things, that I noticed while comparing the results of the runs with the two different databases (let's call them 'microbial' and 'extended'), that I don’t quite understand:
-	The kraken run with the extended database classified about 22% more reads. Alright, But the increase was not only in the section of fungi (there it increased about 8-fold) but also in all other domains (bacteria, archaea, etc) the number of classified reads increased significantly by around 20%. I checked both databases, they were definitely build from the same libraries, except for the deliberately added fungi, and have pretty much the same size in all areas except fungi. 
I’d understand small differences, but 22% more classified read is a lot, and **by number most of the added reads fall into bacteria**, so I am confused.
-	Then i compared the sequence ids of all classified reads in both runs. I’d expected, that the increase in classified reads in the extended run is due to previously unclassified reads, that were now classified. But comparing the sequence ids, there is a significant fraction of reads that is unique to each database, not only the extended database. In the run using the microbial database, 11% of classified reads were only classified using this database, even tough it already classified a lot less reads in total. So it’s **not only less, but also partly a different section of the metagenome?** Can that happen? For the extended database it was 27% of reads that were unique to this database run.
 
I’ve rebuild the databases, and run kraken2 twice to make sure there were no errors. The runs were identical except in all parameters except the databases. Here is the command:
 `kraken2 --use-names --db $database --threads 80 --classified-out classified#.fasta --unclassified-out unclassified#.fasta --report kraken.report --output R1R2.kraken --paired QC_reads_R1.fq QC_reads_R2.fq`

Maybe it’s important to add, that only a small fraction of the metagenomic reads are classified at all, about ¾ remain unclassified in all runs. Is there maybe too much garbage in the data? But it was filtered for host (plant) contamination and human reads

Thank you in advance, 
Best Sonja

**Comment by jenniferlu717** [comment]
First, just to check, are you using the most recent kraken2 version? There used to be some non-deterministic parts to the kraken2 database build but we have fixed that now

Second, I would also use `--minimum-hit-groups 3` (or 4) when running `kraken2,` which minimizes false positives resulting from the minimizer compression we use in the kraken 2 database build. The default is 2, but I've found more success with a higher minimum hit groups. 

Third, I would also include `--confidence 0.05` at least which requires more kmers/minimizers in a read to be identified before the read is classified. 

I'm not certain if these will fix the differences but it might. Another thing to note is the reason why our standard database builds only download **complete** and **chromosome** level assemblies is due to the contamination that we have found in draft genomes (even in refseq). It may be that the fungal genomes added have minimizers that are similar to those of the bacteria, but I am not certain.

Apologies for all of the confusion/differences in defaults. I havent noticed an issue like this before but I've never run this test either. It is interesting. 


Oh, another note. if you redownloaded bacteria/archaea, then the genomes may have slight changes/differences/additions in the newest database.

**Comment by SonWende** [comment]
Hey, thank for you answer and the clarification why you only use **complete**  and **chromosome** level assemblies. With only 50 something fungal genomes that fulfill this criterium, maybe it's better to focus on bacteria/archaea then.

I'm using Kraken 2.1.0. For the database i didn't redownload the bacteria/archaea databases and instead copied them, to have the exact same input files. 

Rerunning both databases with  `--minimum-hit-groups 4` and `--confidence 0.05` reduced the difference in the number of classified reads a lot. The extended database now classified only ~2.5 % more reads instead of 22% more, like it did before. But the number of total reads classified in total also dropped of course (from ~30% to 20 %). Still, this seems more reliable, thank you for the tip.

**Comment by AndrewJWallace** [comment]
My group has found a confidence interval of 0.5, rather than 0.05, to be most useful in order to keep false positives to near-zero. This comes at a price in terms of more unclassified reads and fewer reads able to be classified right down to the species level however.

If you want to test how well your settings are working, download a high quality assembly of a species from NCBI's website, and then use a tool like RTG Tools to generate a million simulated reads from that assembly using the error rates your sequencing technology has, and then put those reads through Kraken and see what level of accuracy the outcome has. That should give you an idea regarding what to expect from your own sequence data.

My own experiences with trying to extend the Kraken database to include other assemblies makes me strongly agree with Jennifer that you should steer clear of any assemblies not marked complete or chromosome, as they are highly likely to mistakenly include pieces of other species and hence reduce the identification capabilities of your Kraken DB if they are included in it.

**Comment by jenniferlu717** [comment]
I'm glad that the addition of those parameters helped @SonWende You can also look into using the eupathdb that I've made here: http://ccb.jhu.edu/data/eupathDB/ and ftp://ftp.ccb.jhu.edu/pub/data/EuPathDB48 which has more eukaryotic pathogen genomes (including fungi). These genomes are mostly draft genomes but I've filtered out a good amount of sequences - removing both low complexity sequences and potentially contaminating sequences. We have been able to use these sequences in our own kraken2 databases.

@AndrewJWallace is also correct that increasing confidence will decrease the false positives further but it also will increase unclassified reads. 

Hopefully all of this helps! I'm going to close this issue but feel free to open a new one if you have other questions
