### ISSUE TITLE
-nan% error when runnung kraken2

### ISSUE THREAD

**Issue by LordSmurph** [DerrickWood/kraken2#404]
I’m struggling with getting kraken2 to run.
I downloaded the Bacteria database to build a kraken2 db
 
 
/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/kraken2-build --download-library bacteria --use-ftp --db db_bac_nt_kraken
 
/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/kraken2-build --download-taxonomy --use-ftp --db db_bac_nt_kraken
 
/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/kraken2-build --build --db db_bac_nt_kraken/
 
I Chose the nt db because the raw reads are nucleotide reads.
 
Now when I run kraken2:
 
/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/kraken2 --db/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/db_bacteria/db_bac_prot/kraken2_db/db_bac_nt_kraken --threads 40 --use-names --paired --report test_report --output test --classified-outcseqs#.fq ../../9_bacterial_reads/full_data/UPUS_Pool2/UPUS_Pool2_megahit_weightedmegan_bowtie_pairedconcordant1.fastq ../../9_bacterial_reads/full_data/UPUS_Pool2/UPUS_Poo2_megahit_weightedmegan_bowtie_pairedconcordant2.fastq
 
I get the following:
 
Loading database information... done.
0 sequences (0.00 Mbp) processed in 0.016s (0.0 Kseq/m, 0.00 Mbp/m).
  0 sequences classified (-nan%)
  0 sequences unclassified (-nan%)

Any suggestions? 

Thank you

**Comment by AGalanis97** [comment]
Hi,

it helps a lot if you add kraken2 scripts and the databases to your PATH variable so you don't need to write the entire thing each time! For example, if you have both the scripts and databases in your PATH variable you can enter the directory of your read files and simply run:
`kraken2 --db db_bac_nt_kraken [ALL OTHER OPTIONS YOU WANT]`
To do this you can look at the manual, but if you need help I can assist you :)

Regardless, it is generally good practice (especially if it's the first time using kraken2) to inspect the library you have built. You can simply run:

`kraken2-inspect --db [LOCATE YOUR DATABASE]`
(In case the scripts are in your PATH variable, you will need to run /phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/kraken2-inspect)

It will tell you how many sequences exist per taxon, which will also tell you that the database building was successful. However from looking at your commands I would say that the database building was ok - unless you received error messages during the building.

From the command you run kraken2 I see the following issues:
1) you haven't specified the db. You have added this:
`/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/kraken2 --db/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/db_bacteria/db_bac_prot/kraken2_db/db_bac_nt_kraken`
but (unless this is a mistake from copying and pasting) you need to add a space between the db and /phylodata/[etc etc].

2) From the scripts you have provided the database should be located at:
`/phylodata/fdalgrande/Max_metagenomics/2020-07_Bactera_MG-MB/11_assembly_free/kraken2/kraken2/db_bac_nt_kraken`
unless you moved it to the location you specify in your script.

3) I am a little bit afraid that it also can't properly locate the fastq files, due to the ".." I see. I don't think it's an issue that's why I also added here as number 3 on the list.

**Comment by jenniferlu717** [comment]
@LordSmurph that error typically happens if kraken is having problems reading the reads in your files. Try this modification to your command: 

`kraken2 --db db_bac_nt_kraken --threads 40 --use-names --paired --report test_report --classified-out seqs.fq ../../9_bacterial_reads/full_data/UPUS_Pool2/UPUS_Pool2_megahit_weightedmegan_bowtie_pairedconcordant1.fastq ../../9_bacterial_reads/full_data/UPUS_Pool2/UPUS_Poo2_megahit_weightedmegan_bowtie_pairedconcordant2.fastq > sample_krakenout.txt`

**Comment by LordSmurph** [comment]
Thank you both, it was solved by adding the PATH variable and running the command from root
