### ISSUE TITLE
kraken2-build and limited RAM recommendations

### ISSUE THREAD

**Issue by bbartholdy** [DerrickWood/kraken2#410]
Hi,

I am trying to build the standard Kraken 2 database, but my computer only has 16GB RAM.

Do you have any recommendations what I should set for the `--kmer-len` and `--minimizer-len` options?

**Comment by jenniferlu717** [comment]
Rather than modifying --kmer-len/--minimizer-len, you can use any of the pre-built databases here: https://benlangmead.github.io/aws-indexes/k2 

We provide an 8GB version of the standard database. There will be less overall sequences classified but the --kmer-len and --minimizer-len were kept at  the default (which is what we tested had the highest accuracy). 

If you really do want to build your own, specifying --max-db-size 8000000000 (i think thats 8GB) would limit the database size.

I hope that helps!

**Comment by bbartholdy** [comment]
Ah, I didn't realise there were pre-built databases. 

Thanks!
