### ISSUE TITLE
Scientific names of taxids

### ISSUE THREAD

**Issue by misazaa** [DerrickWood/kraken2#47]
Hi!

I'm running kraken 2 to do the taxonomic classification of some microbiome data (assembly of PE reads) and I'm using the greengages databased. I want to get to know all the taxonomic classification of each taxids (all the leves) just like the output of kraken-translate, but I only get one level of taxonomy. I run the following lines:

kraken2-build --db./Kraken/ggdatabase --special greengages  
(to build the database)

kraken2 --db ./Kraken/ggdatabase exported/dna-sequences.fasta > output_kraken.txt 
(to do the classification)

kraken2 --db ./Kraken/ggdatabase --use-names exported/dna-sequences.fasta > output_kraken_names.txt 
(To get the scientific names)

Any ideas on how to deal with this would be very much appreciated!

Camila

**Comment by DerrickWood** [comment]
Which version of Kraken 2 are you running? There was a bug that affected the 16S database taxonomies, but that was fixed with the https://github.com/DerrickWood/kraken2/commit/ee24dd32626e77324b0c6f3682e0a9d00c4b7917 commit. From your description, I think you may be encountering this issue, and could fix it by getting the 2.0.7 version (and rebuilding the greengenes database using that new version).

**Comment by misazaa** [comment]
I'm running the 2.0.7-beta version. When you say rebuilding the greengenes database it would be just running again the line: kraken2-build --db./Kraken/ggdatabase --special greengages? Because I tried this lines to classify some samples:

kraken2-build --db ./Kraken/ggdatabase --special greengenes

kraken2 --db ./Kraken/ggdatabase --report E1R1.txt E1R1exported/dna-sequences.fasta > E1R1.txt
kraken2 --db ./Kraken/ggdatabase --report E1P1.txt E1P1exported/dna-sequences.fasta > E1P1.txt

kraken-biom E1R1.txt E1P1.txt
biom convert -i table.biom -o otu_table.txt --to-tsv --header-key taxonomy

And the OTU_IDs that I get are not Greengages identifiers. So I was wondering if kraken2 uses their own identifiers and how can I get a fasta file with all the secuences per OTU_ID or the equivalences go kraken identifiers and greengenes identifiers

**Comment by DerrickWood** [comment]
Kraken 2 does indeed currently use its own ID numbers that aren't Greengenes IDs. Looking through the code now, I'm not certain why I chose to do that - but there is a `seqid2taxid.map` file that should be in the `./Kraken/ggdatabase` directory you created that would give you a mapping between Greengenes IDs and Kraken 2 IDs.

I will take a closer look at this to see if it makes sense to just use the Greengenes IDs as the external IDs here, and if so, I'll change the code to do that so people don't need to go through the trouble of using the `seqid2taxid.map` file.

**Comment by misazaa** [comment]
Thank you Derrick for your answer

I tried using the file seqid2taxid.map but there are some ID numbers present in my OTU table that I can't find in that file, for example the first one, the 667 and there are some, like the 1190 that are related to more than one ID. The other thing is that I don't know what each column means, I guess the second column has the kraken ids and maybe the first one are greengenes identifiers but I though greengenes used numbers with 6 digits and most of the identifiers of the first column have just 4 digits, so I'm not really sure how to get the exact greengenes identifiers for each OTU ID with the seqid2taxid.map file. It would be great if you could give me more insight on this.

I'm attaching my OTU table without taxonomy 

[otu_table.txt](https://github.com/DerrickWood/kraken2/files/2385300/otu_table.txt)

Thanks in advance!

**Comment by DerrickWood** [comment]
You're right about the two columns in `seqid2taxid.map` - the first is the Greengenes ID, and the second is the Kraken 2 ID. There are some instances where multiple Greengenes IDs are associated with the same Kraken 2 ID here, such as Greengenes IDs 16, 17, and 20:

    $ grep '^\(16\|17\|20\)        ' ggtest/data/gg_13_5_taxonomy.txt 
    16	k__Archaea; p__Euryarchaeota; c__Methanococci; o__Methanococcales; f__Methanocaldococcaceae; g__Methanocaldococcus; s__
    20	k__Archaea; p__Euryarchaeota; c__Methanococci; o__Methanococcales; f__Methanocaldococcaceae; g__Methanocaldococcus; s__
    17	k__Archaea; p__Euryarchaeota; c__Methanococci; o__Methanococcales; f__Methanocaldococcaceae; g__Methanocaldococcus; s__

In these cases, however, the actual taxonomy information appears to be identical. In the example above, all three IDs correspond to the _Methanocaldococcus_ genus; the three entries appear to be three different species' 16S sequences, but the species information is not present in the downloaded taxonomy file. Kraken 2's reassignment of IDs came about because of this; Kraken needs a unique ID for each node to build its tree information.

As for Greengenes ID 667, I don't see that in the file (`gg_13_5_taxonomy.txt`) that I downloaded from the Greengenes FTP server. I'm not familiar enough with Greengenes to know why or how their IDs might disappear or be replaced.

**Comment by jenniferlu717** [comment]
I'm going to close this issue for now. The kraken2 code has been updated significantly in the last year, so I'm not sure if this issue still persists, but if you continue to have problems with this, please open a new issue.
