### ISSUE TITLE
kraken2-build --add-to-library too restrictive if sequences without acc.no present

### ISSUE THREAD

**Issue by rwst** [DerrickWood/kraken2#50]
Given a file having both thousands of sequences with accession numbers, and one sequence without accession number, `kraken2-build --add-to-library` will refuse to add the file. This is not necessary, especially because `scan_fasta_file.pl` takes a `--lenient` switch that causes it to ignore sequences without accession numbers. All it takes is to add that switch to the invocation of `scan_fasta_file.pl` in `add_to_library.sh`:
```
diff --git a/scripts/add_to_library.sh b/scripts/add_to_library.sh
index e4987e0..876d79b 100755
--- a/scripts/add_to_library.sh
+++ b/scripts/add_to_library.sh
@@ -25,7 +25,7 @@ fi
 add_dir="$LIBRARY_DIR/added"
 mkdir -p "$add_dir"
 prelim_map=$(cp_into_tempfile.pl -t "prelim_map_XXXXXXXXXX" -d "$add_dir" -s txt /dev/null)
-scan_fasta_file.pl "$1" > "$prelim_map"
+scan_fasta_file.pl --lenient "$1" > "$prelim_map"
 
 filename=$(cp_into_tempfile.pl -t "XXXXXXXXXX" -d "$add_dir" -s fna "$1")
 
```

**Comment by DerrickWood** [comment]
I'm of a divided mind on this - your issue #51 also hits this point as well - but I'm unsure that I want a user who's adding their own data to not have a noticeable failure if a sequence lacks an accession number. If the data is user-selected (rather than one of the `--download-library` sets), then I think it's reasonable to abort the add, flag it to the user, and let them decide what they want to do about it. They could, of course, just add a `kraken:taxid` token to that sequence's header if they know what they want to do with that sequence. But the "loud warning" here could also be helpful in letting them know that they've got some sequences that lack assigned taxonomy information, especially because they (presumably) selected those specific sequences to add in.

While I don't have any issue with an individual user making the change you've suggested to the `add_to_library.sh` script, I'm unconvinced that it should be the default mode of operation (although I'm open to further discussion on the point).

**Comment by rwst** [comment]
I think I agree to that, coming from software design myself.

**Comment by fgvieira** [comment]
I agree that it should not be the default and that there should be a warning message to the user, but it would be nice if it was possible to use that flag from the `kraken2-build` command (e.g.):
```
kraken2-build --lenient  --add-to-library input.fas --db DB
```

Otherwise, the user has to go through all the sequences and remove them from the input file.
