### ISSUE TITLE
Excluding taxa in Kraken DB

### ISSUE THREAD

**Issue by jtamames** [DerrickWood/kraken2#56]
Hello
For testing the performance of Kraken2 in a known set of genomes, I would like to exclude these when creating the kraken database from nr. Would it work if I just simply remove their entries from the nodes.dmp and names.dmp taxonomy files? Otherwise, is there any way in which I can do this?
Best,
Javier

**Comment by DerrickWood** [comment]
Removing those entries from the actual taxonomy data could cause some issues during the build, due to the sequences being mapped to now-missing taxa. I think the better way would be to have the `seqid2taxid.map` file be created (step 1 of the build), then Ctrl+C the build and remove the entries in `seqid2taxid.map` that correspond to the genomes or taxa that you want to exclude. Then you could issue your `kraken2-build --build` command again and build a database with those entries excluded.
