### ISSUE TITLE
what's the meaning of "minimizers of the k-mers" in kraken2?

### ISSUE THREAD

**Issue by jianglikun** [DerrickWood/kraken2#6]
In the introduction of kraken2 ,you said kraken2 if differ from kraken with the minimizers of the k-mers?
could you  introduce it in some detail to make it easier to understand?

**Comment by DerrickWood** [comment]
We are currently working on a manuscript to further clarify some of the implementation details of Kraken 2. Are you specifically asking for information on what a minimizer is?

**Comment by jianglikun** [comment]
yes,what a minimizer is?
Congratulations on your post the kraken2's paper, i am looking forward for this publication.

**Comment by tseemann** [comment]
@jianglikun See http://homolog.us/blogs/blog/2017/10/25/intro-minimizer/

**Comment by jianglikun** [comment]
@tseemann Thankyou！

**Comment by brbatv** [comment]
Hello,
So if we choose l=k , the behaviour would be the same as of kraken1 ?

**Comment by jianglikun** [comment]
@brbatv I think it wil be the same。But
in kraken1，the defult k-mer is 31bp，minimizer is15
in kraken2，the defult k-mer is 35bp，minimizer l is 31

**Comment by DerrickWood** [comment]
@brbatv If l=k, behavior will be very similar to Kraken 1, but output will be slightly different in a small percentage of input sequences due to Kraken 2's use of a probabilistic data structure. Additionally, if seeking to make Kraken 2 operate as close to Kraken 1 as possible, you'd also want to have it not use spaces in the minimizers (i.e., use `kraken2-build --minimizer-spaces 0` when building a database).

**Comment by jianglikun** [comment]
@tseemann If i have two reads that from two differet species,but they completely identical,how kraken classify them??

**Comment by tseemann** [comment]
@jianglikun kraken will classify them at the "most recent common ancestor" of those two species. in some cases this will be "Bacteria".
