### ISSUE TITLE
Kraken causes potential mismatch on k-mer Level

### ISSUE THREAD

**Issue by pfeiferd** [DerrickWood/kraken2#707]
Hi,

consider the following example sequence for kraken2:

@FP200005993L1C029R04400746873
CTAATTAACTTAACAGTTTAAGTAATTTAATTAACATAG
+
GGGGIDFHFGEFGFEHHEEFFGHGFHHGEHHGHGBGGIH

kraken2-2.1.2 (on PowerMac) gives me:

U	FP200005993L1C029R04400746873	0	39	412418:5

However, when I blast the sequence against NCBI databases (Complete genomes and Draft genomes and Complete plasmids) and 412418 using 

https://blast.ncbi.nlm.nih.gov/Blast.cgi

I do not get a single hit. Is this a bug in kraken2 or am I doing something wrong?

I used the DB "Standard 8" (k2_standard_08gb_20221209) from here:
https://benlangmead.github.io/aws-indexes/k2

Thanks,
Daniel

**Comment by pfeiferd** [comment]
(I can offer more of such examples...)

**Comment by AzizHN** [comment]
What confidence are you working with ?

**Comment by pfeiferd** [comment]
> What confidence are you working with ?

Its all defaults... Like this:
kraken2 -db /Users/dpfeifer/dev/bioinf/kraken2-2.1.2/dbs/k2_standard_08gb_20221209 /Users/dpfeifer/problem2.fastq

**Comment by AzizHN** [comment]
I tried to run some experiments the last few days. and I have the same thing.

BLASTING reads done a percentage of 1253/1266 mismatches !

**Comment by pfeiferd** [comment]
> I tried to run some experiments the last few days. and I have the same thing.
> 
> BLASTING reads done a percentage of 1253/1266 mismatches !

The kraken2 paper talks about a probabilistic hash table with an error rate of 1% - which is "generally speaking" very high for such purposes. That woud explain your miscounts which is in the range of 1%. Unfortunately in my data it seems considerably higher. It is particularly disconcerting that 5 kmers in a row got a mismatch in my example from above ... (I will be able to deliver more examples within the next weeks.) I might program a tool that automatically test for mismatches via blastn (in Java)...
I really hope this DOES NOT invalidate all the research any professional analysis built on top of kraken2...

**Comment by pfeiferd** [comment]
Has their been some (more or less rigrorous) functional testing of kraken2? (I have not read the source code and have not checked for test code there either.)

**Comment by DerrickWood** [comment]
Kraken 2's paper does indeed talk about a probabilistic hash table with a non-zero error rate. Note that it also discusses the fact that k-mers are NOT stored in its hash table, but rather minimizers are, and the minimizer of a k-mer is queried against the table, with the minimizer's associated taxid used as the k-mer's taxid. That is why runs of consecutive k-mers will often share a taxid.

Also note that in v2.0.9, we introduced the `--minimum-hit-groups` option (with a default of 2) to require multiple hit groups (a set of overlapping k-mers with the same minimizer) to exist prior to making a classification. The example in the first post here failed this criterion, so it was unclassified (see the `U` at the beginning of the line and `0` in the third column).

None of the data discussed in this issue is a bug in Kraken 2.
