### ISSUE TITLE
building a custom database

### ISSUE THREAD

**Issue by lalalagartija** [DerrickWood/kraken2#89]
Hi, 

I am trying to make a custom Kraken2 database with bacteria, archaea, fungi, viruses and some "added" genomes. It seems to work until I do the classification where I got only 25% of my reads classified. The kraken2-inspect command gives me more than 99% of eukaryotes (added ) and 0.04 % of bacteria but I did the building after downloading bacteria and the rest. What could be the problem ? 

(The Bacteria library is bigger than the added library so I should see bacteria in my final database)

**Comment by nhvanlie** [comment]
Hi there,

I am having a similar problem but with the plant database and flower sequences. Did you find a solution or figure out anything further?

**Comment by jenniferlu717** [comment]
If you provide command lines, we can potentially help. Given that its been awhile since these issues were opened, if you still have problems and need help, please open a new issue and provide the command lines you used to build the databases (and add the genomes into your db). 

Also, if you check to make sure the sequence IDs are in seqid2taxid.map, that should tell you whether the genomes were included in the db build.
